from collections.abc import Callable, Sequence
from typing import Any

__version__: str

class Tool:
    def __init__(self, name: str, description: str, schema: dict[str, Any], callback: Callable[[dict[str, Any]], Any]) -> None: ...

class McpTools:
    @staticmethod
    async def connect(command: str, args: Sequence[str] = ...) -> McpTools: ...
    def names(self) -> list[str]: ...

class Agent:
    @staticmethod
    def openai(model: str, api_key: str, instructions: str | None = ..., base_url: str | None = ..., tools: Sequence[Tool] | None = ..., mcp: McpTools | None = ..., storage_path: str | None = ..., temperature: float | None = ..., modalities: Sequence[str] | None = ..., audio_format: str | None = ..., audio_voice: str | None = ...) -> Agent: ...
    @staticmethod
    def anthropic(model: str, api_key: str, instructions: str | None = ..., tools: Sequence[Tool] | None = ..., mcp: McpTools | None = ..., storage_path: str | None = ..., max_tokens: int = ...) -> Agent: ...
    async def run(self, input: str) -> str: ...
    async def run_session(self, session_id: str, input: str) -> str: ...
    async def run_structured(self, input: str, schema: dict[str, Any]) -> Any: ...
    async def run_multimodal(self, parts: Sequence[dict[str, Any]]) -> dict[str, Any]: ...
    async def run_stream(self, input: str, callback: Callable[[dict[str, Any]], Any]) -> dict[str, Any]: ...

class Team:
    @staticmethod
    def openai(model: str, api_key: str, members: Sequence[tuple[str, str, Agent]]) -> Team: ...
    async def run(self, input: str) -> str: ...

class Retriever:
    def __init__(self, dimensions: int = ..., path: str | None = ..., hybrid: bool = ...) -> None: ...
    async def upsert(self, documents: Sequence[dict[str, Any]]) -> None: ...
    async def retrieve(self, query: str, limit: int = ...) -> list[dict[str, Any]]: ...

class WorkflowBuilder:
    def __init__(self, name: str, checkpoint_directory: str, version: str = ..., max_steps: int = ...) -> None: ...
    def entry(self, node: str) -> None: ...
    def node(self, name: str, callback: Callable[[dict[str, Any]], dict[str, Any]], max_attempts: int = ..., timeout_seconds: float | None = ...) -> None: ...
    def edge(self, source: str, target: str) -> None: ...
    def route(self, source: str, label: str, target: str) -> None: ...
    def join(self, predecessors: Sequence[str], target: str) -> None: ...
    def interrupt_before(self, node: str) -> None: ...
    def build(self) -> WorkflowGraph: ...

class WorkflowGraph:
    async def run(self, execution_id: str, state: Any) -> dict[str, Any]: ...
    async def resume(self, execution_id: str, state_update: Any | None = ...) -> dict[str, Any]: ...
    async def recover(self, execution_id: str) -> dict[str, Any]: ...
